#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 21 23:07:02 2023

@author: mouhsine
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

# read the file using pandas libreries
file_pathe="~/Downloads/hp.csv"
hp=pd.read_csv(file_pathe)
##print(hp) # now we return the varaible string in dummies varaible 
dummies=pd.get_dummies(hp.town)
##print(dummies) # her we add our dummies to the data 
merg=pd.concat([hp,dummies],axis='columns')
##print(merg)  
  # but her we need to drop one varaible to avoid the ureliable result this a statistics issue ??
# the linear model regression classe drop it automatically if we not do this 
final=merg.drop(['town','west windsor'],axis='columns') 
print(final)

# this stage is the train our model
model= LinearRegression()
# a good idea to do this , because we a lot of columns
x=final.drop(['price'], axis='columns') # look at this genuis edia 
y=final.price
model.fit(x,y)
print(model.predict([[2800,0,1]]))
print(model.predict([[3400,0,0]]))
print(model.score(x, y))